# Generated by Django 5.1.7 on 2025-05-06 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_storage', models.BigIntegerField(default=0)),
                ('storage_limit', models.BigIntegerField(blank=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('plan_name', models.CharField(choices=[('Free', '免費方案'), ('BASIC', '基本方案'), ('STANDARD', '標準方案'), ('PREMIUM', '高級方案')], default='Free', max_length=10)),
                ('plan_expire_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_usage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
