# Generated by Django 5.1.7 on 2025-04-11 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postimage_height_postimage_width_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
