# Generated by Django 5.1.7 on 2025-06-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_postvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summery',
            field=models.TextField(blank=True, help_text='文章摘要, 用於 SEO 或文章列表顯示', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='文章縮圖 URL, 用於文章列表或社交媒體分享', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.JSONField(default=dict, help_text='文章內容, 可以是 HTML 或其他格式的內容'),
        ),
    ]
