# Generated by Django 5.1.7 on 2025-06-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_summery_post_thumbnail_url_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='文章縮圖 URL, 用於文章列表或社交媒體分享', max_length=1800, null=True),
        ),
    ]
