# Generated by Django 5.1.7 on 2025-06-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', '開放所有人'), ('private', '只限本人'), ('followers', ' 只限追蹤者'), ('members', '只限會員')], default='public', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已發布')], default='draft', max_length=20),
        ),
    ]
